<?php

return [

    'snappystats-booking-platform' => [
        'id'          => 'snappystats-booking-platform',
        'type'        => 'video',
        'quote'       => 'I\'ve work with this company on many web projects and mobile project and always they were very helpful and understand fast what we need and they develop what we ask in a good delay and price. I recommend this company for any project you have.',
        'author_name' => 'François C.',
        'author_role' => 'Managing Director',
        'company'     => 'SnappyStats',
        'company_url' => 'https://snappystats.ch',
        'rating'      => 5,
        'industry'    => 'Sport Shooting / Training & Education',
        'region'      => 'Europe (remote collaboration)',
        'technologies'=> ['Laravel', 'Blade', 'MySQL'],
        'featured'    => true,
        'contexts'    => [
            'home',
            'service_custom_software',
            'industry_sports_training',
        ],
        'video_url'   => 'https://www.youtube.com/watch?v=zRz7dLUKbjg',
    ],

    'bloomford-hiring-portal' => [
        'id'          => 'bloomford-hiring-portal',
        'type'        => 'text',
        'quote'       => 'I would recommend QalbIT to everybody. QalbIT has been developing all my front-end & backend systems complete to my requirements. They have excellent technical knowledge and listen very well to the needs of their customers. And above all, they are great people.',
        'author_name' => 'Wouter Santens',
        'author_role' => 'Executive Search Consultant at Bloomford',
        'company'     => 'Bloomford',
        'company_url' => 'https://bloomford.be',
        'rating'      => 5,
        'industry'    => 'Recruitment / HR Tech',
        'region'      => 'Belgium (remote-first collaboration)',
        'technologies'=> ['PHP', 'Vue.js', 'MySQL'],
        'featured'    => true,
        'contexts'    => [
            'home',
            'service_custom_software',
            'industry_hr_tech',
            'industry_recruitment',
        ],
        'video_url'   => null,
    ],

    'bocsit-courier-platform' => [
        'id'          => 'bocsit-courier-platform',
        'type'        => 'text',
        'quote'       => 'They listened to my ideas and came up with a plan for development then executed that plan to completion. I liked their attention to detail and communication skills. Very responsive.',
        'author_name' => 'Osmond Mwanyiky',
        'author_role' => 'CTO, Bocsit',
        'company'     => 'Bocsit',
        'company_url' => 'https://bocsit.com',
        'rating'      => 5,
        'industry'    => 'Same-day Local Courier / Logistics',
        'region'      => 'Massachusetts, USA',
        'technologies'=> ['Laravel', 'PHP', 'MySQL'],
        'featured'    => true,
        'contexts'    => [
            'home',
            'service_custom_software',
            'industry_logistics',
            'industry_courier',
        ],
        'video_url'   => null,
    ],

    'londonwide-lmcs-mobile-app' => [
        'id'          => 'londonwide-lmcs-mobile-app',
        'type'        => 'text',
        'quote'       => 'QalbIT successfully developed an app in a timely manner. Their team maximized their knowledge and skills to produce strong deliverables. They were hardworking, effective, and adaptive in the workflow.',
        'author_name' => 'Jonathan Ashby',
        'author_role' => 'Head of Communications & ICT, Londonwide LMCs',
        'company'     => 'Londonwide LMCs',
        'company_url' => 'https://www.lmc.org.uk/',
        'rating'      => 5,
        'industry'    => 'Healthcare / GP Representative Body',
        'region'      => 'London, UK',
        'technologies'=> ['Appcelerator Titanium', 'PHP', 'MySQL'],
        'featured'    => true,
        'contexts'    => [
            'home',
            'service_mobile_app_development',
            'service_custom_software',
            'industry_index',
            'industry_healthcare',
        ],
        'video_url'   => null,
    ],

    'adlunam-investments-multi-projects' => [
        'id'          => 'adlunam-investments-multi-projects',
        'type'        => 'text',
        'quote'       => 'QalbIT is a fantastic dev partner. They provide quality work, good communication and go above and beyond. Fantastic work delivered by QalbIT and his team. Can\'t give enough credits with regards to how they work and at which speed they do it. Top team.',
        'author_name' => 'Joost Hesselberth',
        'author_role' => 'Founder of Ad Lunam Investments PTY LTD',
        'company'     => 'Ad Lunam Investments PTY LTD',
        'company_url' => 'https://adlunam.co.za',
        'rating'      => 5,
        'industry'    => 'Investment & Financial Services',
        'region'      => 'South Africa',
        'technologies'=> ['Laravel', 'JavaScript', 'MySQL'],
        'featured'    => true,
        'contexts'    => [
            'home',
            'service_custom_software',
            'service_saas',
            'industry_fintech',
            'industry_business',
        ],
        'video_url'   => null,
    ],

    'contractor-plus-payments' => [
        'id'          => 'contractor-plus-payments',
        'type'        => 'text',
        'quote'       => 'QalbIT quickly integrated four platforms quickly. Square, Stripe, PayPal, and Coinbase were all successfully used. The vendor provided an active communication process, maintaining timely deadlines despite the research-heavy service. They also offered post-launch support.',
        'author_name' => 'Roshan Sethia',
        'author_role' => 'CTO, Contractor Plus, Inc.',
        'company'     => 'Contractor Plus, Inc.',
        'company_url' => 'https://contractorplus.app/',
        'rating'      => 5,
        'industry'    => 'Construction / Field Services SaaS',
        'region'      => 'United States (remote collaboration)',
        'technologies'=> [
            'CodeIgniter',
            'Stripe',
            'PayPal',
            'Coinbase',
            'WePay',
            'Finix',
            'Payment Gateway Integrations',
        ],
        'featured'    => true,
        'contexts'    => [
            'home',
            'service_payment_gateway',
            'service_custom_software',
            'service_saas',
            'industry_index',
            'industry_construction',
            'industry_field_services',
        ],
        'video_url'   => null,
    ],

    'vizit-egypt-rentals' => [
        'id'          => 'vizit-egypt-rentals',
        'type'        => 'text',
        'quote'       => 'It was a pleasure working with QalbIT Team. Very professional with their work and timeline. Very responsive and easy to work with QalbIT.',
        'author_name' => 'Mostafa Gad',
        'author_role' => 'Founder of Vizit',
        'company'     => 'Vizit',
        'company_url' => 'https://vizit.net/',
        'rating'      => 5,
        'industry'    => 'Short-Stay Rentals / Travel & Hospitality',
        'region'      => 'Egypt',
        'technologies'=> ['Laravel', 'Vue.js', 'MySQL'],
        'featured'    => true,
        'contexts'    => [
            'home',
            'service_custom_software',
            'service_saas',
            'industry_travel',
            'industry_hospitality',
        ],
        'video_url'   => null,
    ],

    'elo-branding-landing-page' => [
        'id'          => 'elo-branding-landing-page',
        'type'        => 'text',
        'quote'       => 'QalbIT\'s Team was excellent to work with and went over and above to ensure the job was completed successfully. Would highly recommend for your website work.',
        'author_name' => 'Kate Allinson',
        'author_role' => 'Co-Founder & CEO at Elo Branding',
        'company'     => 'Elo Branding',
        'company_url' => 'https://elobranding.com/',
        'rating'      => 5,
        'industry'    => 'Branding / Creative Agency',
        'region'      => 'Global / Remote',
        'technologies'=> ['WordPress'],
        'featured'    => true,
        'contexts'    => [
            'home',
            'service_web_development',
            'service_wordpress',
            'industry_agency',
            'industry_marketing',
        ],
        'video_url'   => null,
    ],

    'local-buzz-flutter-app' => [
        'id'          => 'local-buzz-flutter-app',
        'type'        => 'text',
        'quote'       => 'Excellent work! QalbIT team delivered the project on time with great quality. Their ability to quickly adapt to new requirements and deliver promptly was impressive. Highly recommend them for Flutter projects.',
        'author_name' => 'Ahmed G',
        'author_role' => 'Founder at Local Buzz',
        'company'     => 'Local Buzz',
        'company_url' => null,
        'rating'      => 5,
        'industry'    => 'Consumer App / Local Discovery',
        'region'      => 'Global / Remote',
        'technologies'=> ['Flutter', 'Laravel', 'MySQL'],
        'featured'    => true,
        'contexts'    => [
            'home',
            'service_mobile_app_development',
            'service_custom_software',
            'service_flutter',
        ],
        'video_url'   => null,
    ],

    'heuvelman-multi-apps' => [
        'id'          => 'heuvelman-multi-apps',
        'type'        => 'text',
        'quote'       => 'We have been working with the QalbIT team for a long time. They are very fast, reliable and have excellent communication. Highly recommended for development work.',
        'author_name' => 'Ivo Kuipers',
        'author_role' => 'Solution Architect at Heuvelman Sound & Vision B.V.',
        'company'     => 'Heuvelman Sound & Vision B.V.',
        'company_url' => 'https://www.heuvelman.nl/',
        'rating'      => 5,
        'industry'    => 'Audiovisual / Events & Installations',
        'region'      => 'The Netherlands',
        'technologies'=> ['Appcelerator Titanium'],
        'featured'    => true,
        'contexts'    => [
            'home',
            'service_mobile_app_development',
            'service_custom_software',
            'industry_index',
            'industry_av',
            'industry_events',
        ],
        'video_url'   => null,
    ],

    'netzur-wordpress-site' => [
        'id'          => 'netzur-wordpress-site',
        'type'        => 'video',
        'quote'       => 'Working with QalbIT was an absolute pleasure. They understood our brand vision, delivered a WordPress site that is easy to navigate, and kept communication smooth throughout. I would absolutely recommend them to anybody.',
        'author_name' => 'Imdad Ali Kadiwala',
        'author_role' => 'Founder, Netzur',
        'company'     => 'Netzur',
        'company_url' => 'https://netzur.com',
        'rating'      => 5,
        'industry'    => 'ISP Software / SaaS',
        'region'      => 'India',
        'technologies'=> ['WordPress'],
        'featured'    => true,
        'contexts'    => [
            'home',
            'service_web_development',
            'service_wordpress',
            'industry_isp_software',
            'industry_saas',
        ],
        'video_url'   => 'https://www.youtube.com/shorts/0uGRPp1jSp4',
    ],

];
